/*
 * This Java source file was generated by the Gradle 'init' task.
 */


import com.twelfthmile.yuga.utils.Constants;
import com.twelfthmile.yuga.Yuga;
import org.json.JSONArray;
import org.junit.jupiter.api.Test;
import org.skyscreamer.jsonassert.JSONAssert;

import java.io.File;
import java.util.Date;
import java.util.HashMap;

public class YugaTest {
    @Test
    public void main() throws Exception {

        File testInput = new File("src/test/in/yuga_test.json");
        File expectedResults = new File("src/test/in/yuga_result.json");
        if (testInput.exists() && expectedResults.exists()) {
            JSONArray jsonArr = new JSONArray(Util.readFile(testInput));
            JSONArray expectedResultArray = new JSONArray(Util.readFile(expectedResults));

            HashMap<String, String> configMap = new HashMap<String, String>();
            configMap.put(Constants.YUGA_CONF_DATE, Constants.dateTimeFormatter().format(new Date(118, 1, 1)));

            StringBuilder out = new StringBuilder("[");
            for (int i = 0; i < jsonArr.length(); i++) {
                String s = jsonArr.getString(i);
                out.append(Yuga.parse(s, configMap).print()).append(",");
            }
            if (out.length() > 1)
                out.setLength(out.length() - 1);
            String ret = out.append("]").toString();
            ret = new JSONArray(ret).toString(2);
            JSONArray resultArray = new JSONArray(ret);
            try {
                JSONAssert.assertEquals(expectedResultArray, resultArray, true);
            } catch (AssertionError ae) {
                Util.writeToFile(resultArray.toString(2), "src/test/out/yuga_result.json");
                Util.writeToFile(ae.getMessage(), "src/test/out/yuga_test.log");
                throw ae;
            }
        }
    }
}
